"use client";
import { useEffect, useState, type FormEvent } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import CourseHeader from "@/components/education/CourseHeader";
import { getConfiguredSupabaseClient } from "@/lib/supabase-browser";
import { roleLandingPath } from "@/lib/auth";
import type { UserRole } from "@/lib/types";
export default function AuthPage() {
  const router=useRouter();
  const [mode,setMode]=useState<"signin"|"signup"|"forgot">("signin"),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[confirm,setConfirm]=useState(""),[signedIn,setSignedIn]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[error,setError]=useState("");
  useEffect(()=>{getConfiguredSupabaseClient().then(async(client)=>setSignedIn(Boolean((await client.auth.getSession()).data.session))).catch((err)=>setError(err.message));},[]);
  async function submit(event:FormEvent) {event.preventDefault();setBusy(true);setError("");setMessage("");try {const client=await getConfiguredSupabaseClient();
    if(mode==="signup") {if(password.length<8 || password!==confirm) throw new Error("密码至少 8 位，且两次输入需一致。");const {error}=await client.auth.signUp({email:email.trim(),password,options:{emailRedirectTo:`${location.origin}/auth/callback`}});if(error) throw error;setMessage("注册请求已提交。请检查邮箱验证邮件，再登录。新账号只有学生权限。");}
    else if(mode==="forgot") {const {error}=await client.auth.resetPasswordForEmail(email.trim(),{redirectTo:`${location.origin}/auth/reset-password`});if(error) throw error;setMessage("若账号可接收重置邮件，请按邮件链接设置新密码。");}
    else {const {data,error}=await client.auth.signInWithPassword({email:email.trim(),password});if(error) throw error;if(!data.session) throw new Error("尚未取得登录会话，请重试。");setSignedIn(true);const response=await fetch("/api/me",{headers:{Authorization:`Bearer ${data.session.access_token}`}});const payload=await response.json();if(!response.ok) throw new Error("登录成功，但账号角色暂时无法读取。");router.push(roleLandingPath(payload.user.role as UserRole));}
  } catch(err) {setError((err as Error).message);} finally {setBusy(false);} }
  return <div className="edu-app"><CourseHeader active="auth" /><main className="edu-auth"><div className="edu-eyebrow">课程账号 / EDUCATIONAL PSYCHOLOGY</div><h1>回到你的学习现场</h1><p>账号保存正式学习记录；无需账号也可以查看课程地图与样板流程。</p><section className="edu-panel">{signedIn ? <><h2>你已经登录</h2><div className="edu-actions"><Link className="edu-button" href="/student">我的学习</Link><button className="edu-button secondary" disabled={busy} onClick={async()=>{setBusy(true);try {const {error}=await (await getConfiguredSupabaseClient()).auth.signOut();if(error) throw error;setSignedIn(false);setMessage("已退出登录。");} catch(err) {setError((err as Error).message);} finally {setBusy(false);}}}>退出登录</button></div></> : <><div className="edu-tabs">{([['signin','登录'],['signup','注册学生账号'],['forgot','忘记密码']] as const).map(([id,name])=><button className={mode===id?"active":""} key={id} onClick={()=>{setMode(id);setMessage("");setError("");}}>{name}</button>)}</div><form onSubmit={submit}><label htmlFor="email">邮箱</label><input id="email" type="email" required autoComplete="email" value={email} onChange={(e)=>setEmail(e.target.value)} />{mode!=="forgot" && <><label htmlFor="password">密码</label><input id="password" type="password" required minLength={8} autoComplete={mode==="signup"?"new-password":"current-password"} value={password} onChange={(e)=>setPassword(e.target.value)} /></>}{mode==="signup" && <><label htmlFor="confirm">再次输入密码</label><input id="confirm" type="password" required autoComplete="new-password" value={confirm} onChange={(e)=>setConfirm(e.target.value)} /><p className="edu-caption">教师与研究者角色由管理员单独配置，注册表单不能申请或提升权限。</p></>}<button className="edu-button" disabled={busy} type="submit">{busy?"正在处理…":mode==="signin"?"登录课程":mode==="signup"?"注册":"发送重置邮件"}</button></form></>}{error && <p className="edu-inline-error" role="alert">{error}</p>}{message && <p role="status">{message}</p>}</section><Link className="edu-text-link" href="/preview">先看看教学脚手架 →</Link></main></div>;
}
