"use client";
import { useState } from "react";
import Link from "next/link";
import { COURSE, GROUPS, TASKS, UNITS } from "@/lib/education/course";
import CourseHeader from "./CourseHeader";
export default function CourseHome() {
  const [selected, setSelected] = useState(6);
  const unit = UNITS.find((item) => item.id === selected)!;
  const task = TASKS[selected];
  return <div className="edu-app"><CourseHeader /><div className="edu-topline"><span>外语学习 × 教育心理学</span><span>课程 {COURSE.id} · {COURSE.hours} 学时 / {COURSE.credits} 学分 · 第一版</span></div><div className="edu-course-layout"><aside className="edu-map" aria-label="课程单元"><div className="edu-map-heading"><h2>课程地图</h2><span>15 单元</span></div>{GROUPS.map((group, index) => <section key={group}><h3>{String(index + 1).padStart(2, "0")} / {group}</h3>{UNITS.filter((item) => item.group === index).map((item) => <button className={`edu-unit ${item.id === selected ? "is-selected" : ""}`} aria-pressed={item.id === selected} key={item.id} onClick={() => setSelected(item.id)}><span className="edu-unit-number">{String(item.id).padStart(2, "0")}</span><span>{item.title}{item.ready && <small>完整样板</small>}</span></button>)}</section>)}</aside>
    <main className="edu-course-main"><div className="edu-eyebrow">{GROUPS[unit.group]} / 单元 {String(unit.id).padStart(2, "0")} / {unit.hours} 学时</div><h1>{unit.title}</h1><p className="edu-question">{unit.question}</p><div className="edu-tags">{unit.concepts.map((concept) => <span key={concept}>{concept}</span>)}</div><section className="edu-focus"><div className="edu-section-label">本单元，你将尝试</div><h2>{unit.objective}</h2>{task ? <><p>{task.caseText}</p><div className="edu-actions"><Link className="edu-button" href={`/student?unit=${unit.id}`}>进入单元学习 <span>→</span></Link><Link className="edu-button secondary" href={`/preview?unit=${unit.id}`}>预览脚手架</Link></div><p className="edu-caption">样板需由教师审核发布后用于课程学习。预览不会提交作业或产生研究数据。</p></> : <><p>本单元已纳入课程地图。任务和材料将由教师按教学进度审核发布，第一版先开放第 6、9 单元的完整样板。</p><Link className="edu-text-link" href="/instructor">查看教师工作台 →</Link></>}</section>
    <section className="edu-learning-path"><h2>一次学习，留下理解变化</h2><ol><li><b>01</b><strong>先作解释</strong><span>写出你自己的判断</span></li><li><b>02</b><strong>按需获得支持</strong><span>提示、概念、部分示范</span></li><li><b>03</b><strong>换情境应用</strong><span>不依赖提示独立尝试</span></li><li><b>04</b><strong>回看与修订</strong><span>保存你确认的理解记录</span></li></ol></section><section className="edu-bottom-grid"><div><h3>从自己的语言学习出发</h3><p>用课程概念理解词汇、听说读写、反馈与跨文化交际。区分“发生了什么”和“我怎样解释”。</p></div><div><h3>课程考核保持不变</h3><div className="edu-assessment">{COURSE.assessment.map((part) => <span key={part.label}><b>{part.weight}%</b>{part.label}</span>)}</div><p className="edu-caption">对话次数不是成绩。作业与论文由任课教师依据课程要求评定。</p></div></section></main></div><footer className="edu-footer">依据 2026 年 8 月课程教学大纲 · 教、学、研一体化课程分支 <span>学习记录由你确认，教学判断由教师负责。</span></footer></div>;
}
