"use client";
import { useEffect, useRef, useState } from "react";
import Link from "next/link";
import { ACTIVE_UNIT_IDS, INTERVENTIONS, STAGES, TASKS, UNITS, getInterventionForUnit, type Task } from "@/lib/education/course";
import type { Analytics, LearningSession } from "@/lib/education/types";
import CourseHeader from "./CourseHeader";
import AccessNotice from "./AccessNotice";
import { educationApi, useEducation } from "./useEducation";

export default function TeacherWorkspace() {
  const { data, loading, error: accessError, refresh } = useEducation();
  const [unit, setUnit] = useState(6), [draft, setDraft] = useState<Task>(TASKS[6]), [week, setWeek] = useState(7), [notes, setNotes] = useState(""), [reviewed, setReviewed] = useState(false);
  const [stats, setStats] = useState<Analytics | null>(null), [session, setSession] = useState<LearningSession | null>(null), [feedback, setFeedback] = useState("");
  const [research, setResearch] = useState(false), [protocol, setProtocol] = useState(""), [notice, setNotice] = useState(""), [approved, setApproved] = useState(false);
  const [busy, setBusy] = useState(false), [message, setMessage] = useState(""), [error, setError] = useState(""), [invite, setInvite] = useState("");
  const feedbackId = useRef<string | null>(null);
  const current = data?.configs.find((item) => item.task.unitId === unit);
  useEffect(() => { setDraft(structuredClone(current?.task ?? TASKS[unit])); setWeek(current?.scheduledWeek ?? getInterventionForUnit(unit)!.week!); setNotes(current?.teacherNotes ?? ""); setReviewed(false); }, [current?.version, unit]);
  useEffect(() => { if (data?.user.role === "instructor") { setResearch(data.settings.researchEnabled); setProtocol(data.settings.researchProtocol); setNotice(data.settings.consentNotice); void educationApi<Analytics>("?view=teaching").then(setStats).catch((err) => setError(err.message)); } }, [data]);
  async function run(work: () => Promise<void>) { setBusy(true); setError(""); setMessage(""); try { await work(); } catch (err) { setError((err as Error).message); } finally { setBusy(false); } }
  const change = (key: keyof Task, value: unknown) => { setDraft((old) => ({...old,[key]:value})); setReviewed(false); };
  return <div className="edu-app"><CourseHeader active="instructor" />{!data || data.user.role !== "instructor" ? <AccessNotice loading={loading} error={accessError} mismatch={data ? "教师权限由管理员配置，学生注册不能自行取得。" : ""} onRetry={refresh} /> : <main className="edu-page">
    <div className="edu-page-heading"><div><div className="edu-eyebrow">教 / 课程工作台</div><h1>把支持放在需要的地方</h1><p>审核任务、发布脚手架，回看学生的解释变化。这里不生成认知能力排名。</p></div><Link className="edu-button secondary" href="/preview">预览学生流程 →</Link></div>
    {!data.classroomEnabled && <div className="edu-callout">课堂数据采集尚未开放：管理员需完成独立数据库、角色权限、隐私告知与运行配置，才能接收正式学生。</div>}
    <section className="edu-panel"><h2>模型与干预计划</h2><p>新会话：{data.ai.provider === "deepseek" ? "DeepSeek 官方 API" : data.ai.provider === "openai" ? "OpenAI" : "配置错误"} / {data.ai.model || "—"} · {data.aiEnabled ? "密钥已配置（仍需实际联调）" : "密钥尚未配置，教师固定提示可用"}。</p><p className="edu-caption">模型选择在开始会话时保存，不自动回退。要切换供应商须由管理员显式配置，并记录研究方案偏离。现有记录保留原任务和模型信息。</p><div className="edu-tags">{INTERVENTIONS.map((item) => <span key={item.id}>干预 {item.id} · {item.ready ? `Week ${item.week}` : "讲义待选"}</span>)}</div></section>
    <section className="edu-metrics">{[["已加入课程",stats?.members],["学习记录",stats?.total],["完成四阶段",stats?.completed],["AI 答疑轮次",stats?.chats]].map(([label,value]) => <div key={label}><span>{label}</span><strong>{value ?? "—"}</strong></div>)}</section>
    <section className="edu-panel"><div className="edu-panel-title"><h2>课堂入口</h2><button className="edu-button secondary" disabled={busy} onClick={() => run(async () => { const result = await educationApi<{code:string}>("",{action:"invite"}); setInvite(result.code); setMessage("邀请码已生成。更新后旧码失效，已经加入的学生不受影响。"); await refresh(); })}>{data.settings.inviteEnabled ? "更新课程邀请码" : "生成课程邀请码"}</button></div><p>学生登录后输入邀请码加入课程。研究参与另行选择，不能作为加入条件。</p>{invite && <p className="edu-invite">本次邀请码：<strong>{invite}</strong><small>只在本次操作后显示，请通过课程渠道发放。</small></p>}</section>
    <section className="edu-panel"><div className="edu-panel-title"><h2>课程任务与脚手架</h2><span className="edu-caption">干预 1 / Week 7 · 干预 2 / Week 10 · 后三次待选讲义</span></div><div className="edu-tabs" role="group" aria-label="选择编辑单元">{ACTIVE_UNIT_IDS.map((id) => <button key={id} className={unit === id ? "active" : ""} onClick={() => setUnit(id)} disabled={busy}>干预 {getInterventionForUnit(id)!.id} · {UNITS[id-1].title}</button>)}</div>
      <p className="edu-caption">当前：{current ? `v${current.version} · ${current.published ? "已发布" : "草稿"}` : "未发布样板"}。新版本不会改写学生已经开始的任务快照。旧版记录不自动算作本轮干预。修改前请保存当前任务。</p>
      <button className="edu-button secondary" disabled={busy} onClick={() => {setDraft(structuredClone(TASKS[unit]));setWeek(getInterventionForUnit(unit)!.week!);setReviewed(false);}}>载入本次讲义样板（替换编辑区，尚不发布）</button>
      <div className="edu-form-grid"><label>教学周<input type="number" min={1} max={30} value={week} onChange={(e) => setWeek(Number(e.target.value))} /></label><label>任务标题<input value={draft.title} maxLength={100} onChange={(e) => change("title",e.target.value)} /></label></div>
      <label>学习目标<textarea rows={2} value={draft.objective} onChange={(e) => change("objective",e.target.value)} /></label>
      <label>案例情境<textarea rows={4} value={draft.caseText} onChange={(e) => change("caseText",e.target.value)} /></label>
      <details className="edu-editor-details" open><summary>四阶段任务问题</summary>{STAGES.map((stage) => <label key={stage.id}>{stage.title}<textarea rows={3} value={draft.prompts[stage.id]} onChange={(e) => change("prompts",{...draft.prompts,[stage.id]:e.target.value})} /></label>)}</details>
      <details className="edu-editor-details"><summary>三层提示与概念工具箱</summary>{draft.hints.map((hint,index) => <label key={index}>第 {index+1} 层提示<textarea rows={3} value={hint} onChange={(e) => change("hints",draft.hints.map((value,i) => i === index ? e.target.value : value))} /></label>)}{draft.concepts.map((concept,index) => <div className="edu-form-grid" key={index}><label>概念名称<input value={concept.term} onChange={(e) => change("concepts",draft.concepts.map((value,i) => i === index ? {...value,term:e.target.value} : value))} /></label><label>概念解释<textarea value={concept.text} onChange={(e) => change("concepts",draft.concepts.map((value,i) => i === index ? {...value,text:e.target.value} : value))} /></label></div>)}</details>
      <label>自我检查标准（每行一项）<textarea rows={4} value={draft.criteria.join("\n")} onChange={(e) => change("criteria",e.target.value.split("\n"))} /></label>
      <label>课程材料与来源说明<textarea rows={2} value={draft.source} onChange={(e) => change("source",e.target.value)} /></label>
      <label>教师补充（学生与 AI 均可见）<textarea rows={2} maxLength={2000} value={notes} onChange={(e) => {setNotes(e.target.value);setReviewed(false);}} /></label>
      <label className="edu-check"><input type="checkbox" checked={reviewed} onChange={(e) => setReviewed(e.target.checked)} />我已审核本任务的事实、来源、提示层次与完成标准。</label>
      <div className="edu-actions">{[false,true].map((published) => <button key={String(published)} className={`edu-button ${published ? "" : "secondary"}`} disabled={busy || !reviewed} onClick={() => run(async () => { await educationApi("",{action:"publish",unitId:unit,expectedVersion:current?.version ?? 0,task:draft,scheduledWeek:week,teacherNotes:notes,reviewed,published}); await refresh(); setMessage(published ? "任务新版本已发布。" : "已保存为未发布草稿，学生不能开始此版本。"); })}>{published ? "发布新版本" : "保存为草稿 / 停止新开任务"}</button>)}</div>
    </section>
    <section className="edu-panel"><div className="edu-panel-title"><h2>教学观察与反馈</h2><button className="edu-button secondary" disabled={busy} onClick={() => run(async () => setStats(await educationApi<Analytics>("?view=teaching")))}>刷新记录</button></div><p className="edu-caption">次数反映使用情况，不代表理解水平。请结合具体回答与课堂表现判断。学生以稳定学习编号显示，不显示邮箱。</p>{stats?.truncated && <p role="alert">记录超过本版读取上限，当前统计不完整。</p>}
      {!stats?.rows.length ? <p className="edu-empty">暂无真实学习记录。</p> : <div className="edu-table-wrap"><table><thead><tr><th>学习编号</th><th>干预 / 教学周 / 单元 / 版本</th><th>阶段</th><th>提示 / 对话</th><th>记录</th></tr></thead><tbody>{stats.rows.map((row) => <tr key={row.id}><td>{row.learnerCode}</td><td>{row.interventionId ? `干预 ${row.interventionId}` : "旧版"} / Week {row.scheduledWeek} / {row.unitId} / v{row.taskVersion}</td><td>{row.stage === "complete" ? "完成" : STAGES.find((s) => s.id === row.stage)?.short}</td><td>{row.hints} / {row.chats}</td><td><button className="edu-text-link" disabled={busy} onClick={() => run(async () => {setSession((await educationApi<{session:LearningSession}>(`?session=${row.id}`)).session);setFeedback("");feedbackId.current=null;})}>查看轨迹</button></td></tr>)}</tbody></table></div>}
      {session && <div className="edu-review-record"><div className="edu-panel-title"><h3>单元 {session.unitId} · 任务 v{session.task.version}</h3><button className="edu-text-link" onClick={() => setSession(null)}>收起</button></div>{session.entries.map((entry) => <article className="edu-understanding" key={entry.id}><strong>{entry.kind === "ai_error" ? "AI 请求失败（不计成功对话）" : entry.kind === "chat" ? "AI 对话" : entry.kind === "hint" ? `提示 ${entry.level}` : entry.kind === "feedback" ? "教师反馈" : STAGES.find((stage) => stage.id === entry.stage)?.short}</strong><p className="edu-prewrap">{entry.text}</p>{entry.reply && <p className="edu-ai-reply edu-prewrap">{entry.reply}</p>}<small>{new Date(entry.createdAt).toLocaleString("zh-CN")} {entry.provider && ` · ${entry.provider} / ${entry.model} · ${entry.promptVersion}`} {entry.errorCode && ` · ${entry.errorCode}`}</small></article>)}<label>留给学生的反馈<textarea rows={3} maxLength={2000} value={feedback} onChange={(e) => {setFeedback(e.target.value);feedbackId.current=null;}} /></label><button className="edu-button" disabled={busy || !feedback.trim()} onClick={() => run(async () => { feedbackId.current ??= crypto.randomUUID(); await educationApi("",{action:"feedback",sessionId:session.id,text:feedback,requestId:feedbackId.current}); setSession((await educationApi<{session:LearningSession}>(`?session=${session.id}`)).session); setFeedback("");feedbackId.current=null;setMessage("反馈已保存，学生可在理解轨迹中查看。"); })}>保存教师反馈</button></div>}
    </section>
    <section className="edu-panel"><h2>研究开关与告知</h2><p>默认关闭。开启不等于学生同意；学生须单独选择。告知更新后，研究端只读取重新同意的记录。</p><label className="edu-check"><input type="checkbox" checked={research} onChange={(e) => setResearch(e.target.checked)} />开启自愿研究参与入口</label>{research && <><label>研究方案名称 / 编号<input value={protocol} maxLength={200} onChange={(e) => setProtocol(e.target.value)} /></label><label>研究告知（目的、数据、保存期限、访问范围、退出方式与负责人）<textarea rows={7} value={notice} maxLength={4000} onChange={(e) => setNotice(e.target.value)} /></label><label className="edu-check"><input type="checkbox" checked={approved} onChange={(e) => setApproved(e.target.checked)} />方案和告知已完成所需审核，研究不是成绩或课程参与的条件。</label></>}
      <button className="edu-button secondary" disabled={busy || (research && !approved)} onClick={() => run(async () => {await educationApi("",{action:"settings",researchEnabled:research,researchProtocol:protocol,consentNotice:notice,approved});await refresh();setMessage("研究设置已保存。");})}>保存研究设置</button>
    </section>
  </main>}{(error || message) && <div className={`edu-toast ${error ? "error" : ""}`} role={error ? "alert" : "status"}>{error || message}</div>}</div>;
}
